# Generated by Django 4.0 on 2022-01-14 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sitelocation', models.CharField(db_column='siteLocation', max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('mastername', models.CharField(db_column='masterName', max_length=255)),
                ('installationdatetime', models.DateTimeField(db_column='installationDatetime')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=255)),
                ('sensortype', models.CharField(db_column='sensorType', max_length=255)),
                ('compressor', models.CharField(max_length=255)),
                ('installationdatetime', models.DateTimeField(db_column='installationDatetime')),
                ('masterid', models.ForeignKey(db_column='masterId', on_delete=django.db.models.deletion.DO_NOTHING, to='sensorManagement.master')),
            ],
        ),
    ]
